CREATE TABLE IF NOT EXISTS sites (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NOT NULL,

  PRIMARY KEY (id),
  UNIQUE KEY (link)
);
