CREATE TABLE IF NOT EXISTS users (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `username_upper` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_upper` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `balance` FLOAT(25) NOT NULL DEFAULT '5',

  PRIMARY KEY (id),
  UNIQUE KEY (email)
);
